"""
Git Operations for Auto-Fix Pipeline (Issues #003, #004).

Provides:
- commit_patch: Git commit with auto-fix message
- rollback_patch: Restore original files and revert commit
"""

from __future__ import annotations
import logging
import os
import subprocess
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database.models.auto_fix import AutoFixBackup, AutoFixLog
from database.models.canonical import FrontendError

logger = logging.getLogger(__name__)

# Git identity for auto-fix commits
GIT_AUTHOR_NAME = "NovelOS Auto-Fix"
GIT_AUTHOR_EMAIL = "bot@novelos.dev"

# Commit message template
COMMIT_TEMPLATE = """auto-fix: 修复 {error_type} 错误

Error: {error_message}
Fingerprint: {fingerprint}
Patch-ID: {patch_id}

Auto-generated by ErrorFixPipeline"""


async def commit_patch(
    patch_id: str,
    modified_files: list[str],
    db: AsyncSession,
    push: bool = False,
) -> dict[str, Any]:
    """
    Execute git commit for a patch.

    Args:
        patch_id: UUID of the patch
        modified_files: List of file paths to commit
        db: Database session
        push: Whether to push to remote branch

    Returns:
        {"commit_hash": str, "push_status": str}
    """
    # Fetch log entry
    result = await db.execute(
        select(AutoFixLog).where(AutoFixLog.patch_id == patch_id)
    )
    log_entry = result.scalar_one_or_none()

    if not log_entry:
        logger.error(f"commit_patch: No log entry found for patch_id {patch_id}")
        return {"commit_hash": "", "push_status": "failed"}

    # Get error details
    error_result = await db.execute(
        select(FrontendError).where(FrontendError.id == log_entry.error_id)
    )
    error = error_result.scalar_one_or_none()

    if not error:
        logger.error(f"commit_patch: No error found for error_id {log_entry.error_id}")
        return {"commit_hash": "", "push_status": "failed"}

    try:
        # Get repo root (assumes we're in backend/ or similar)
        repo_root = _find_git_repo_root()
        if not repo_root:
            logger.error("commit_patch: Not in a git repository")
            return {"commit_hash": "", "push_status": "failed"}

        # Create branch name
        branch_name = f"auto-fix/{patch_id}"

        # Git commands (using subprocess for safety)
        git_cmds = _build_commit_commands(
            repo_root=repo_root,
            branch_name=branch_name,
            modified_files=modified_files,
            commit_msg=_format_commit_message(error, patch_id),
            push=push,
        )

        # Execute commands
        commit_hash = ""
        push_status = "pending"

        for cmd in git_cmds:
            result = subprocess.run(
                cmd,
                cwd=repo_root,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode != 0:
                logger.error(f"commit_patch: Git command failed: {cmd}\n{result.stderr}")
                push_status = "failed"
                break

            # Extract commit hash from 'git rev-parse HEAD'
            if "rev-parse" in cmd:
                commit_hash = result.stdout.strip()
                push_status = "applied"

            # Update push status if push succeeded
            if "push" in cmd and push:
                push_status = "pushed"

        # Update log entry
        log_entry.commit_hash = commit_hash
        log_entry.push_status = push_status
        await db.commit()

        return {"commit_hash": commit_hash, "push_status": push_status}

    except subprocess.TimeoutExpired:
        logger.error("commit_patch: Git command timeout")
        return {"commit_hash": "", "push_status": "failed"}
    except Exception as e:
        logger.error(f"commit_patch: Unexpected error: {e}")
        return {"commit_hash": "", "push_status": "failed"}


async def rollback_patch(
    patch_id: str,
    db: AsyncSession,
    rollback_reason: str = "verification_failed",
) -> dict[str, Any]:
    """
    Execute rollback for a patch.

    Steps:
    1. Restore original file content from backup
    2. Git checkout/reset to original state
    3. Delete auto-fix branch if exists

    Args:
        patch_id: UUID of the patch to rollback
        db: Database session
        rollback_reason: Reason for rollback

    Returns:
        {"rolled_back": bool, "rollback_at": datetime}
    """
    rollback_time = datetime.utcnow()

    # Fetch log entry
    result = await db.execute(
        select(AutoFixLog).where(AutoFixLog.patch_id == patch_id)
    )
    log_entry = result.scalar_one_or_none()

    if not log_entry:
        logger.error(f"rollback_patch: No log entry found for patch_id {patch_id}")
        return {"rolled_back": False, "rollback_at": None}

    # Fetch backups
    backup_result = await db.execute(
        select(AutoFixBackup).where(AutoFixBackup.patch_id == patch_id)
    )
    backups = backup_result.scalars().all()

    if not backups:
        logger.warning(f"rollback_patch: No backups found for patch_id {patch_id}")

    try:
        repo_root = _find_git_repo_root()
        if not repo_root:
            logger.error("rollback_patch: Not in a git repository")
            return {"rolled_back": False, "rollback_at": None}

        branch_name = f"auto-fix/{patch_id}"

        # 1. Restore files from backup
        for backup in backups:
            file_path = os.path.join(repo_root, backup.file_path)
            if os.path.exists(file_path):
                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(backup.original_content)
                logger.info(f"rollback_patch: Restored {backup.file_path}")

        # 2. Git checkout/reset
        git_checkout_cmd = ["git", "checkout", "--", "."]
        subprocess.run(
            git_checkout_cmd,
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=30,
        )

        # 3. Delete branch if exists
        git_branch_delete_cmd = ["git", "branch", "-D", branch_name]
        subprocess.run(
            git_branch_delete_cmd,
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=30,
        )

        # Update log entry
        log_entry.status = "rolled_back"
        log_entry.rollback_at = rollback_time
        await db.commit()

        return {"rolled_back": True, "rollback_at": rollback_time}

    except subprocess.TimeoutExpired:
        logger.error("rollback_patch: Git command timeout")
        return {"rolled_back": False, "rollback_at": None}
    except Exception as e:
        logger.error(f"rollback_patch: Unexpected error: {e}")
        return {"rolled_back": False, "rollback_at": None}


def _find_git_repo_root() -> str | None:
    """Find the git repository root directory."""
    # Start from current directory and walk up
    current = os.getcwd()
    while current:
        git_dir = os.path.join(current, ".git")
        if os.path.isdir(git_dir):
            return current
        parent = os.path.dirname(current)
        if parent == current:  # Reached root
            return None
        current = parent
    return None


def _build_commit_commands(
    repo_root: str,
    branch_name: str,
    modified_files: list[str],
    commit_msg: str,
    push: bool,
) -> list[list[str]]:
    """Build sequence of git commands for commit."""
    commands = []

    # 1. Create and checkout branch
    commands.append(["git", "checkout", "-b", branch_name])

    # 2. Add modified files
    for file_path in modified_files:
        commands.append(["git", "add", file_path])

    # 3. Commit with custom author
    commands.append([
        "git", "commit",
        "-m", commit_msg,
        "--author", f"{GIT_AUTHOR_NAME} <{GIT_AUTHOR_EMAIL}>",
    ])

    # 4. Get commit hash
    commands.append(["git", "rev-parse", "HEAD"])

    # 5. Push if requested
    if push:
        commands.append(["git", "push", "-u", "origin", branch_name])

    return commands


def _format_commit_message(error: FrontendError, patch_id: str) -> str:
    """Format commit message for auto-fix."""
    return COMMIT_TEMPLATE.format(
        error_type=error.type,
        error_message=error.message[:200],  # Truncate long messages
        fingerprint=error.fingerprint,
        patch_id=patch_id,
    )


# Export for testing
__all__ = [
    "commit_patch",
    "rollback_patch",
    "_format_commit_message",
    "_find_git_repo_root",
    "GIT_AUTHOR_NAME",
    "GIT_AUTHOR_EMAIL",
    "COMMIT_TEMPLATE",
]